### ISSUE TITLE
Weird typing issue with Arabic text

### ISSUE THREAD

**Issue by memoday** [matecat/MateCat#421] opened 2016-09-21 12:31 UTC
Hi support team,

I was trying to edit the automated translation and for some reason, sometimes MateCat freezes up on me. Using arrows to move also hangs and eventually I had to copy the text and paste it in Notepad, edited it and then paste it back in MateCat. Also, putting the cursor in the middle of a word breaks it up. It looks like a visual issue, but very annoying. 

Are you aware of these issues?

thanks,
Mohamed

**Comment by Ostico** [comment] 2016-09-21 13:33
Hi @memoday , thank you for the report, we will investigate as soon as possible.

**Comment by riccio82** [comment] 2016-09-23 11:34
We fixed the bug in arabic translations where the cursor (click and arrows) break the words into single letters. The fix is in development, It will be in production in about a week.
About the freeze we could not reproduce the problem. can you give me some more information?

**Comment by memoday** [comment] 2016-09-26 05:29
Once you put the cursor and do editing, try to move the cursor to the right or the left and you will it hangs there for while. Put the cursor within a word, then try to use the left arrow to move to the left and you should see it freezing there.

**Comment by riccio82** [comment] 2016-09-27 09:46
Hi @memoday,
 we fix also this behaviour with the preious commit. You will see it in production as sonn as possible.
Thanks!

**Closed** 2016-09-27 09:46 UTC
Labels: assigned to engineers
