### ISSUE TITLE
Segments with tags do not change their status to "Translated" when they are 100% matched from a private TM

### ISSUE THREAD

**Issue by robot-xliff-farmer** [matecat/MateCat#896] opened 2017-08-07 14:30 UTC
When applying a private TM, only the segments without tags are changing their status to "Translated" and thus do not require a human interaction.
All the segments with inline tags are remaining in a "New" status though show 100% match in Translation matches pane. This require a translator to do a monkey job of manually changing their status to "Translated"

Attached is an archive with source file and TMX. The link to a problem segment: https://www.matecat.com/translate/matecat-test-apply-tm-nocr/ru-RU-en-US/866693-59a1ca4ce893#523611435

[Archive3.zip](https://github.com/matecat/MateCat/files/1205120/Archive3.zip)

**Comment by alessandrocattelan** [comment] 2017-12-29 14:51
Hello. I am sorry but I cannot reproduce the issue. Can you try again and let me know if this is still an issue or if I did not understand your query?

I created a project uploading the files in Archive3.zip to MateCat and selecting the option "Pre-translate 100% matches from TM". What I get is a job which is entirely marked as Translated:
https://www.matecat.com/translate/matecatproj-201712290344/ru-RU-en-US/1067821-93b1fbe346fe#611295930

![screen shot 2017-12-29 at 15 50 22](https://user-images.githubusercontent.com/13222990/34439689-050e454e-ecb0-11e7-95f1-f68935f004c2.png)

**Comment by krishnevsky** [comment] 2017-12-29 15:37
Hello, thank you for keeping in touch! This is no longer an issue - it works correctly in the new version of MateCat with our current projects.Happy New Year! 29.12.2017, 17:51, "Alessandro Cattelan" <notifications@github.com>:Hello. I am sorry but I cannot reproduce the issue. Can you try again and let me know if this is still an issue or if I did not understand your query?I created a project uploading the files in Archive3.zip to MateCat and selecting the option "Pre-translate 100% matches from TM". What I get is a job which is entirely marked as Translated:https://www.matecat.com/translate/matecatproj-201712290344/ru-RU-en-US/1067821-93b1fbe346fe#611295930—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- Эми Кришневскиhttp://staff.yandex-team.ru/krishnevsky/

**Comment by Ostico** [comment] 2018-03-07 10:33
Closing

**Closed by Ostico** 2018-03-07 10:33 UTC
Labels: bug, enhancement
