### ISSUE TITLE
Unable to upload file of 20mb size

### ISSUE THREAD

**Issue by BhavyaShukla** [matecat/MateCat#1856] opened 2020-11-26 13:55 UTC
Hello @Ostico 

I am able to upload and translate all files, but for file size of around 20mb. I am getting below error. 
![image](https://user-images.githubusercontent.com/5159978/100358809-97c62800-2fee-11eb-852d-702e0a763e7f.png)

I checked init.php and $MAX_UPLOAD_FILE_SIZE         = 62914560;  

Please let me know if i need to check somewhere else in my instance.

**Comment by Ostico** [comment] 2020-11-26 17:45
The issue is in your web server.

Check your php.ini searching for "max", there are 2 variables, upload size and post size.

**Comment by BhavyaShukla** [comment] 2020-11-27 13:14
@Ostico  I updated the php.ini  with below values:

![image](https://user-images.githubusercontent.com/5159978/100453135-5b5c0000-30b2-11eb-9b2f-1cf89c91f4b8.png)

![image](https://user-images.githubusercontent.com/5159978/100453170-6dd63980-30b2-11eb-8525-3eaeea54f46c.png)

But I will can't even upload a 6mb file.

**Comment by Ostico** [comment] 2020-11-30 10:30
Hi @BhavyaShukla ,
it's really weird that this not worked. To be sure that your modifications are set correctly:

- Do you restarted apache after the changes?
- Do you have modified the right file? `/etc/php/5.6/apache2/php.ini`

**Comment by BhavyaShukla** [comment] 2020-11-30 12:04
Yes, I modified the mentioned file and restarted the apache2 service.  I am not getting the above error, instead the importing is getting stuck at below image.
![image](https://user-images.githubusercontent.com/5159978/100608042-c0f2fb00-3303-11eb-8183-cd4c5aa8d420.png)

And after few minutes it gives the error.
![image](https://user-images.githubusercontent.com/5159978/100608248-07485a00-3304-11eb-8845-b556d767cafc.png)

Small size (less than 2m) files still working fine.
Please let me know if you need any log files.

**Comment by BhavyaShukla** [comment] 2020-11-30 12:13
It was the issue with file format conversion. I am able to upload 20mb docx file now. 
Thanks for your help @Ostico

**Comment by Ostico** [comment] 2020-11-30 12:33
Hi @BhavyaShukla 
welcome. 

So can we close the issue?

**Comment by BhavyaShukla** [comment] 2020-11-30 16:04
Yes, thanks again.

**Closed** 2020-12-01 11:18 UTC
