### ISSUE TITLE
jid=undefined Analysis Page is causing the issue Not getting the standerd waited words waited words

### ISSUE THREAD

**Issue by ravioodles** [matecat/MateCat#2708] opened 2023-03-20 04:06 UTC
Hi Team, hope you are well,  again facing the same issue word count is not working. Can you please update what is going on and what is the issue we are facing ? Did we make any change in the api requests again?

Issue raised number:
2703

![image](https://user-images.githubusercontent.com/46445899/224625263-b18f083f-7a1c-4aec-b30b-b363987c3b38.png)

![image](https://user-images.githubusercontent.com/46445899/224625884-2bfcc1e6-901b-4ef1-9065-327606284e7f.png)

![image](https://user-images.githubusercontent.com/46445899/224626539-0a24d745-ac4e-419c-9230-c9c5bab8542b.png)

http://localhost/?action=getVolumeAnalysis&time=1678711176893,jid=undefined

I am getting the jid=undefined what is the issue because it came suddenly without any change.

Can you please help to resolve the issue.

![image](https://user-images.githubusercontent.com/46445899/224899634-85917466-1cc4-4877-8339-f92b80bb15c8.png)

We have already set the mymemory requests to HTTPS. Please suggest some solution or let us know if any changes are made to configurations.

![image](https://user-images.githubusercontent.com/46445899/225510083-77f05a55-9788-42c1-bb88-c6dc8cea70b0.png)
I am just getting the jid=undefined error in all requests and I have not made any change in the code. The issue has come suddenly from nowhere. Please help me to resolve this ASAP.

![image](https://user-images.githubusercontent.com/46445899/225818760-8f1d027a-1774-4bd0-afc4-562464017c25.png)

Thanks and Regards.

**Comment by HURIMOZ** [comment] 2023-03-21 18:40
Buongiorno @Ostico, stiamo ancora aspettando la tua risposta. Can you help us please?

**Comment by Ostico** [comment] 2023-03-22 14:35
Hi, is this the latest matecat version?

**Comment by ravioodles** [comment] 2023-03-22 17:58
Hi @Ostico thankyou for your response.

**Main issue is that our analysis page is not getting the word counts.**

As we already allobrate this issue in #2584 & and share the log files also there.
Can you please have a look in the issue id #2584 and please help us to know the solution 

Thanks and Regards.

**Comment by ravioodles** [comment] 2023-03-24 11:26
Hi Team any update we are unable to get the error as it is not seems any code issue. Please its urgent can you help.

Thanks and Regards.

**Comment by Ostico** [comment] 2023-03-24 17:50
Hi @ravioodles 
You are running a very old version of Matecat.

I suggest you to update to a newer version.

Anyway,

Perhaps the problem is with the FastAnalysis API which has changed.

The endpoint for FastAnalysis has changed and we've added a redirect to the old one:

```
curl https://api.mymemory.translated.net/analyze
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
</body>
</html>
```

Maybe this is blocking your instance to perform the analysis.

Try to change the code in  `lib/Utils/Engines/MyMemory.php`  with

```php
    public function fastAnalysis( &$segs_array ) {

        if ( !is_array( $segs_array ) ) {
            return null;
        }

        $this->_setAdditionalCurlParams( [
                        CURLOPT_TIMEOUT => 300
                ]
        );

        $this->engineRecord['base_url'] = "https://analyze.mymemory.translated.net/api/v1";

        $this->call( "analyze_url", array_values( $segs_array ), true, true );

        return $this->result;

    }
```


Or add a 
```
CURLOPT_FOLLOWLOCATION => true,
```

in the `_setAdditionalCurlParams` method.

**Comment by ravioodles** [comment] 2023-03-27 02:46
Hi @Ostico Thankyou for you response.

Okay will try to implement your all suggested points and get back to you.

Thanks and Regards. Really appreciated Thankyou.

**Comment by ravioodles** [comment] 2023-03-29 04:02
Hi @Ostico I tried to implement your suggested code in my code base but it doesn't work. Can you please let me know what other changes i can do so it start working. And for taking a fresh pull i have my dependencies that i can't take the latest pull of matecat.

**Comment by Ostico** [comment] 2023-03-30 12:58
Can you post some logs please, i can't help without them. There is a log named `fastAnalysis.log` can you check for errors?

**Comment by ravioodles** [comment] 2023-03-31 07:33
Hi @Ostico below are the logs of fastAnalysis.log
![image](https://user-images.githubusercontent.com/46445899/229049004-64e80713-5594-4bca-8981-4b43c558bfb8.png)
[fastAnalysis.log.zip](https://github.com/matecat/MateCat/files/11119327/fastAnalysis.log.zip)

**Comment by Ostico** [comment] 2023-03-31 09:50
Hi @ravioodles, the log says the patch didn't work. Have you restarted the FastAnalysis daemon?

**Comment by ravioodles** [comment] 2023-03-31 10:40
@Ostico yes we are running these commands to restart the analysis

**Comment by Ostico** [comment] 2023-03-31 13:28
@ravioodles , the only explaination i can imagine is that you do not applied the code on the right source or in the right place.

Can I see you code? do you have a github repo?

**Comment by ravioodles** [comment] 2023-04-03 08:11
Hi @Ostico please provide your mail id so will able to provide the Git access.

**Comment by ravioodles** [comment] 2023-04-06 08:19
Hi @Ostico,

We added you to the our github please accept the invitation and Please guide US to deal with this Issue.

Thanks and regards
Ravi Rose.

**Comment by Ostico** [comment] 2023-04-06 12:39
Hi @ravioodles 

https://github.com/oodlestechnologies/Transleqo-Language-Translation/issues/1

**Comment by ravioodles** [comment] 2023-04-11 12:29
Hi @Ostico Hope you are well,

Yes that patch works but without the array in _setAdditionalCurlParams. Currently it is working but we are testing the full flow and if founds something interrupted or is their any issue in the flow will connect with you.

But thankyou so much for your help. I really appriciate your help, your quick debug time & response time to us. Thankyou.

Thanks and Regards
Ravi Rose

**Comment by Ostico** [comment] 2023-04-13 08:20
You're welcome.

Can I close this issue?

**Comment by ravioodles** [comment] 2023-04-13 08:51
Yes @Ostico you can close it. Thankyou so much once again for the help. Please let us know if any APIs endpoints change in future also. 

Thanks and Regards 
Ravi Rose

**Closed** 2023-05-17 08:29 UTC
