### ISSUE TITLE
Export XLIFF provides original XLIFF instead of translated one.

### ISSUE THREAD

**Issue by vinayaksharmagh** [matecat/MateCat#1865] opened 2020-12-03 09:00 UTC
Hey, in my local setup of matecat when after translating a job I try to download the work using "Export XLIFF", it provides me with the original untranslated XLIFF (without the target text). Although, when I do the same on Matecat's website. the XLIFF contains both source and target text. 
I know that I can use "Export Job TMX" as an alternative but I need to extract trans-unit ids of translation as well which is possible only with XLIFF file.  Please help me out with this.

**Comment by Ostico** [comment] 2020-12-03 09:13
Hi @vinayaksharmagh 
the exported xliff contains the target tag but it is empty?

**Comment by vinayaksharmagh** [comment] 2020-12-03 09:26
No, it doesn't contain target tag at all

**Comment by Ostico** [comment] 2020-12-03 09:28
Please try tu update your matecat version and composer dependencies

**Comment by vinayaksharmagh** [comment] 2020-12-03 09:33
It is a recent version. I have installed it about 2 weeks ago using latest master of that time.

**Comment by Ostico** [comment] 2020-12-03 10:03
We had a recent regression bug on that

**Comment by vinayaksharmagh** [comment] 2020-12-03 10:11
Ok. Actually, I have to use the deployed version right away and setting up the entire thing with a newer version would take time.
Thus, I am thinking about using a workaround for this problem. Can you please tell me if there are other features that might be affected because of this bug so that I can be at lookout for them as well.

**Comment by Ostico** [comment] 2020-12-03 10:42
No this depends on how we rebuild the xliff. Because of the bug if the target tag is not present it will not be added.
A workaround is to add an empty target tag in all the trans-unit.

**Comment by Ostico** [comment] 2020-12-03 10:45
Anyway, to fix the issue a `php composer.phar update` should fix the issue.

**Comment by vinayaksharmagh** [comment] 2020-12-03 11:31
> No this depends on how we rebuild the xliff. Because of the bug if the target tag is not present it will not be added.
> A workaround is to convert manually the xliff and add an empty target tag in all the trans-unit before to upload it in matecat ( assuming that you are using matecat filters ).

This worked like a charm. Thanks!
Although, I am not using matecat filters. I have written a custom XLIFF generator

**Comment by Ostico** [comment] 2020-12-03 12:01
Can we close this issue?

**Comment by vinayaksharmagh** [comment] 2020-12-03 12:02
Yeah sure.

**Closed** 2020-12-03 12:03 UTC
